### ISSUE TITLE
V2 KV engine support

### ISSUE THREAD

**Issue by zszabo14** [nodevault/node-vault#202] opened 2022-08-05 09:19 UTC
Hi

KV2 engine will be supported? When?

`"Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."`

**Comment by aviadhahami** [comment] 2022-11-10 17:10
hi, this is a dupe of #82; place track there for progress :)

**Closed by aviadhahami** 2022-11-10 17:10 UTC
